services:
  pg: 
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: meteo-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: 
      - 54321:5432
    volumes:
      - test_volume:/var/lib/postgresql

volumes:
  test_volume: {}